services:
  app:
    build: ./app
    image: app
    networks:
      - frontend
    ports:
      - 3000:80
    depends_on:
      - api

  api:
    build: ./api
    image: api
    environment:
      - MONGODB_URI=mongodb://db_mongo:27017
    networks:
      - frontend
      - database
    ports:
      - 30000:3000
    depends_on:
      - db_mongo

  db_mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foomin
      - MONGO_INITDB_ROOT_PASSWORD=foobar
    networks:
      - database
    expose:
      - 27017
    volumes:
      - ./data:/data/db

networks:
  database:
  frontend:
