services:
  app:
    build: ./app
    image: app
    ports:
      - 3000:80

  api:
    build: ./api
    image: api
    ports:
      - 5000:80
    environment:
      - MONGODB_URI=db_mongo://db_mongo:db_mongo:27017/db_mongo
    depends_on:
      - db_nosql

  db_mongo:
    image: mongo
    expose:
      - 27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foomin
      - MONGO_INITDB_ROOT_PASSWORD=foobar
    volumes:
      - ./data:/data/db
