services:
  app:
    build: ./app
    image: app
    ports:
      - 3000:80
    networks:
      - frontend

  api:
    build: ./api
    image: api
    ports:
      - 5000:80
    networks:
      - frontend
      - backend

  db_nosql:
    image: mongo
    container_name: db_mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foomin
      - MONGO_INITDB_ROOT_PASSWORD=foobar
    logging:
      options:
        max-size: 256m
    volumes:
      - mongodb_data_container:/data/db

networks:
  frontend:
  backend:


volumes:
  mongodb_data_container:
